name: Gateway service

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: run
      uses: cedrickring/golang-action@1.5.2
      env:
          GO111MODULE: "on"
          PROJECT_PATH: "./service/gateway"
